### PR TITLE
Fix a problem in TitanTableBuilder::Add()

### LINKED ISSUE #232: An issues about TitanTableBuilder::Add()
I am reading the source code of titan, and I found an issue.

In TitanTableBuilder::Add() (pasted in below), there are several "if" & "else" statements, and I want to talking about the assertion in that.
In the last "else", there is an assertion that expecting builder_unbuffered() returns true.
But we can assume such a scenario: 
1. There is a memtable to be flushed, and it includes several **big kvs (i.e., has big value)** and some **blob indexes (i.e., the type of their key is kTypeBlobIndex)** generated by GC. 
2. When flushing, a few big kvs are added to the TitanTableBuilder first with TitanTableBuilder::Add (the below function), which add them in a blob file, and because the number of them is few, the state of BlobfileBuilder is still Buffered.  
3. Then, add a blob index with TitanTableBuilder::Add(), and it will reach the last "else". In this case, because the state of BlobfileBuilder is Buffered, the assertion will fail.

I'm not sure whether my understanding is correct, and it looks like a potential problem.

```
/* titan/src/table_builder.cc */

void TitanTableBuilder::Add(const Slice& key, const Slice& value){

  if (ikey.type == kTypeBlobIndex &&
      cf_options_.blob_run_mode == TitanBlobRunMode::kFallback) {

      ....// processing something only when fallback

   }else if (ikey.type == kTypeValue &&
             cf_options_.blob_run_mode == TitanBlobRunMode::kNormal){

      ....// processing something when encountering kTypeValue keys

   }else if (ikey.type == kTypeBlobIndex && cf_options_.level_merge &&
             target_level_ >= merge_level_ &&
             cf_options_.blob_run_mode == TitanBlobRunMode::kNormal) {

      ....// processing something when running level merge in compaction

   } else { 
    // processing when encountering kTypeBlobIndex or kTypeMerge
    assert(builder_unbuffered()); 
    base_builder_->Add(key, value);
  }
}
```

### PR DESCRIPTION
**Pull request by Borelset**
Close #232.

Fix a problem in a corner case:
Flushing a memtable, and it has a few kTypeValue in the first and follows with a kTypeBlobIndex or kTypeMerge generated by GC.
These kTypeValues are written to a blob file first, which makes the BlobFileBuilder is still in the Buffered state because the size of them is not enough.
In this case, the following kTypeBlobIndex or kTypeMerge must be cached in the workflow of TitanTableBuilder::Add().

### CODE REVIEW

**Review by Connor1996 — COMMENTED** [review]
Please add a test case

**Comment by Borelset** [comment]
> Please add a test case

Ok, I have updated the "DictCompressDisorder" test in titan/src/table_builder_test.cc to cover this case.

**Review by Connor1996 — APPROVED** [review]
LGTM, Please fix the format check and sign-off

File: src/table_builder.cc [hunk 1]
```diff
@@ -122,9 +122,16 @@ void TitanTableBuilder::Add(const Slice& key, const Slice& value) {
...
+  } else {// Mainly processing kTypeMerge and kTypeBlobIndex in both flushing and compaction.
+      if (builder_unbuffered()) {
+          // Directly append when base_builder_ is in unbuffered state
+          base_builder_->Add(key, value);
+      } else {
+          //It must be cached when base_builder_ is in buffered state
+          std::unique_ptr<BlobFileBuilder::BlobRecordContext> ctx =
+                  NewCachedRecordContext(ikey, value);
+          blob_builder_->AddSmall(std::move(ctx));
+      }
```
Comment (Connor1996) [inline src/table_builder.cc:134]: it's repeated for third times, how about extracting a function.

File: src/table_builder.cc [hunk 2]
```diff
@@ -115,16 +106,24 @@ void TitanTableBuilder::Add(const Slice& key, const Slice& value) {
...
+    AddSmallToTableAdaptively(ikey, value);
   } else {
-    assert(builder_unbuffered());
-    base_builder_->Add(key, value);
+    // Mainly processing kTypeMerge and kTypeBlobIndex in both flushing and compaction.
+    AddSmallToTableAdaptively(ikey, value);
+  }
+}
+
+void TitanTableBuilder::AddSmallToTableAdaptively(const ParsedInternalKey& ikey, const Slice& value){
```
Comment (Connor1996) [inline src/table_builder.cc:116]: Rename it to `AddToBaseTable`, and change L59 and L67 too

File: src/table_builder.cc [hunk 3]
```diff
@@ -115,16 +106,24 @@ void TitanTableBuilder::Add(const Slice& key, const Slice& value) {
...
+  if (builder_unbuffered()) {
+    // We can directly append this into SST safely, without disorder issue.
+    // Only when base_builder_ is in unbuffered state
+    base_builder_->Add(ikey.user_key, value);
+  } else {
+    // We have to let builder to cache this KV pair, and it will be returned
+    // when state changed
```
Comment (Connor1996) [inline src/table_builder.cc]:
```suggestion
    // We have to let builder to cache this KV pair, and it will be flushed to base table
    // when the state changes to unbuffered
```

**Comment by Borelset** [comment]
There seems to be some problem with the sign-off setting of this PR, and I plan to resubmit a new one.

**Comment by Connor1996** [comment]
> There seems to be some problem with the sign-off setting of this PR, and I plan to resubmit a new one.

No bother, it's okay now

File: src/table_builder.cc (hunk 2 above)
Comment (Borelset) [reply src/table_builder.cc]: If so, there will be two AddToBaseTable functions in this class. How about AddSmallToBaseTable?

Comment (Borelset) [reply src/table_builder.cc]: Well, another AddToBaseTable is also adding small values.
I will rename it with AddToBaseTable.

Comment (Connor1996) [reply src/table_builder.cc]: emmm... let's call it `AddSmall`

**Comment by Borelset** [comment]
I have reformat code and rename the function. 
The test results seems ok.

**Review by Connor1996 — APPROVED** [review]

File: src/table_builder.cc [hunk 4]
```diff
@@ -115,16 +106,27 @@ void TitanTableBuilder::Add(const Slice& key, const Slice& value) {
...
+    AddSmall(key, ikey, value);
   } else {
-    assert(builder_unbuffered());
+    // Mainly processing kTypeMerge and kTypeBlobIndex in both flushing and
+    // compaction.
+    AddSmall(key, ikey, value);
+  }
+}
+
+void TitanTableBuilder::AddSmall(const Slice& key,
```
Comment (tabokie) [inline src/table_builder.cc:117]: The naming is still confusing. How about renaming the old `AddToBaseTable` to `AddBlobResultsToBase`, and `AddSmall` to `AddBase` (symmetric to `AddBlob`).

**Review by tabokie — COMMENTED** [review]
Rest looks good.

File: src/table_builder.cc [hunk 5]
```diff
@@ -180,7 +182,7 @@ void TitanTableBuilder::AddBlob(const ParsedInternalKey& ikey,
       cf_options_.blob_file_target_size) {
     // if blob file hit the size limit, we have to finish it
     // in this case, when calling `BlobFileBuilder::Finish`, builder will be in
-    // unbuffered state, so it will not trigger another `AddToBaseTable` call
+    // unbuffered state, so it will not trigger another `AddSmall` call
```
Comment (Connor1996) [inline src/table_builder.cc:185]: is it replaced by mistake?

Comment (Borelset) [reply src/table_builder.cc:185]: Yes, I will fix it.

File: src/table_builder.cc (hunk 4 above)
Comment (Borelset) [reply src/table_builder.cc:117]: ok, I will do these changes.

**Review by tabokie — APPROVED** [review]

**Review by ti-srebot — APPROVED** [review]
