### PR TITLE
Fix wrong assert delta < 0 for cocurrent compaction while flush

### LINKED ISSUE #171: titan_thread_safety_test failed
```
10/14 Test #10: titan_thread_safety_test ...............Child aborted***Exception:   5.00 sec
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from TitanThreadSafetyTest
[ RUN      ] TitanThreadSafetyTest.Insert
[       OK ] TitanThreadSafetyTest.Insert (4173 ms)
[ RUN      ] TitanThreadSafetyTest.InsertAndDelete
Assertion failed: (false), function OnCompactionCompleted, file /Users/travis/build/tikv/titan/src/db_impl.cc, line 1239.
```

occurs in #169

### PR DESCRIPTION
**Pull request by Connor1996**
Because the flushed SST is added to superversion before `OnFlushCompleted()` is called, so if there is a concurrent compaction, `OnCompactionCompleted()` maybe called before `OnFlushCompleted()` is called.
In this case, the state of the blob file generated by the flush is still `kPendingLSM`, while the blob file size delta is for the compaction event. So it is possible that delta is negative.

Fix #171

### CODE REVIEW

File: src/db_impl.cc [hunk 1]
```diff
@@ -1230,14 +1243,29 @@ void TitanDBImpl::OnCompactionCompleted(
...
+          // positive number. And the delta will be subtracted in
+          // `OnFlushCompleted()` later.
+          SubStats(stats_.get(), compaction_job_info.cf_id,
+                   file->GetDiscardableRatioLevel(), 1);
+          file->set_live_data_size(static_cast<uint64_t>(-delta));
+          AddStats(stats_.get(), compaction_job_info.cf_id,
+                   file->GetDiscardableRatioLevel(), 1);
+          ROCKS_LOG_INFO(db_options_.info_log,
+                         "OnCompactionCompleted[%d]: Get blob file %" PRIu64
+                         " live size being negative %lld, maybe due to "
```
Comment (yiwu-arbug) [inline src/db_impl.cc:1265]: use PRIu64 macro instead of `%lld`

File: src/db_impl.cc [hunk 2]
```diff
@@ -1148,6 +1149,18 @@ void TitanDBImpl::OnFlushCompleted(const FlushJobInfo& flush_job_info) {
...
+        // Because the flushed SST is added to superversion before
+        // `OnFlushCompleted()` is called, so if there is a concurrent
+        // compaction, `OnCompactionCompleted()` maybe called before
+        // `OnFlushCompleted()` is called.
+        // In this case, the state of the blob file generated by the flush is
+        // still `kPendingLSM`, while the blob file size delta is for the
+        // compaction event. So it is possible that delta is negative.
+        // It records the delta as a positive number if any, so here subtract it
+        // from the total live data size.
+        delta -= file->live_data_size();
```
Comment (yiwu-arbug) [inline src/db_impl.cc:1162]: Also add some comment in blob_format.h around `BlobFileMeta::live_data_size` to explain what does the value mean when `state_ == kPendingLSM`?

File: src/db_impl.cc [hunk 3]
```diff
@@ -1230,14 +1243,29 @@ void TitanDBImpl::OnCompactionCompleted(
...
-        if (delta < 0) {
-          // Cannot happen..
-          ROCKS_LOG_WARN(db_options_.info_log,
-                         "OnCompactionCompleted[%d]: New blob file %" PRIu64
-                         " live size being negative",
-                         compaction_job_info.job_id, file_number);
-          assert(false);
-          delta = 0;
+        if (delta <= 0) {
+          // Because the flushed SST is added to superversion before
```
Comment (yiwu-arbug) [inline src/db_impl.cc:1247]: It seems to me the same could happen to compaction-generated blob files. Update the comment to reflect that?

File: src/db_impl.cc [hunk 4]
```diff
@@ -1230,14 +1243,29 @@ void TitanDBImpl::OnCompactionCompleted(
...
+          // so if there is a concurrent compaction, `OnCompactionCompleted()`
+          // maybe called before `OnFlushCompleted()` is called.
+          // In this case, the state of the blob file generated by the flush is
+          // still `kPendingLSM`, while the blob file size delta
+          // is for the compaction event. So it is possible that delta is
+          // negative.
+          // To make the live data size accurate, here records the delta as a
+          // positive number. And the delta will be subtracted in
+          // `OnFlushCompleted()` later.
+          SubStats(stats_.get(), compaction_job_info.cf_id,
```
Comment (yiwu-arbug) [inline src/db_impl.cc:1258]: Maybe we shouldn't add discardable-ratio-level stat when the file is still in `kPendingLSM` state?

Comment (Connor1996) [reply src/db_impl.cc:1258]: the discardable-ratio-level is updated when the blob file is added in manifest. But at that time the live_data_size is unknown, so here we need to update the discardable-ratio-level stat.

Comment (Connor1996) [reply src/db_impl.cc:1258]: we have talked about it in this PR https://github.com/tikv/titan/pull/157

Comment (yiwu-arbug) [reply src/db_impl.cc:1258]: lol, sorry, I feel it weird every time.

Comment (Connor1996) [reply src/db_impl.cc:1258]: indeed, will add a todo here.

Comment (Connor1996) [reply src/db_impl.cc]: make it not count zero live data size when adding blob file
